### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by MaikEight** [link3337/ExaltAccountManager#1]
Hey there,
nice little tool you made there, it is still quite bare-bones and plain looking but working!

If you maybe need more inspiration, check out my version of an Exalt Account Manager:
[https://github.com/MaikEight/ExaltAccountManager](https://github.com/MaikEight/ExaltAccountManager) 

Keep it up!

**Comment by link3337** [comment]
Hi and thanks^^,
you obviously put a lot of effort with a lot of extra features into yours, good job man! 

I simply made this for a few friends and then people kept asking me about it so I decided to make it somewhat public.
I also wasn't really motivated to some fancy UI stuff because I am waiting for MAUI's official release (then UI rework).

Maybe one day DECA will release a better API for tools like these. 🦆
